name: smart_expense_tracker
description: A simple Flutter expense tracker with smart insights
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0

  intl: ^0.19.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
